let currentUser=null,currentProfile=null;
function msg(id,text,ok=true){const e=document.getElementById(id);if(!e)return;e.textContent=text||'';e.style.color=ok?'#187a2f':'#b00020'}
async function init(){const {data}=await supabaseClient.auth.getSession();if(data.session)await enterApp(data.session.user);supabaseClient.auth.onAuthStateChange((_e,s)=>{if(s?.user)enterApp(s.user)})}
async function resolveLoginToEmail(login){if(login.includes('@'))return login;const n=login.trim().toLowerCase();const {data}=await supabaseClient.from('profile').select('email, imie_nazwisko').limit(500);const f=(data||[]).find(p=>String(p.imie_nazwisko||'').toLowerCase().replaceAll(' ','-')===n||String(p.imie_nazwisko||'').toLowerCase()===n);return f?.email||login}
function showRegisterView(){document.getElementById('loginView').classList.add('hidden');document.getElementById('registerView').classList.remove('hidden');msg('registerMsg','')}
function showLoginView(){document.getElementById('registerView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden');msg('loginMsg','')}
async function registerAccount(){const email=document.getElementById('registerEmail').value.trim(),pass=document.getElementById('registerPassword').value,pass2=document.getElementById('registerPassword2').value;if(!email)return msg('registerMsg','Wpisz e-mail.',false);if(pass.length<6)return msg('registerMsg','Hasło musi mieć minimum 6 znaków.',false);if(pass!==pass2)return msg('registerMsg','Hasła nie są takie same.',false);const {data,error}=await supabaseClient.auth.signUp({email,password:pass});if(error)return msg('registerMsg',error.message,false);if(data?.user){await supabaseClient.from('profile').upsert({id:data.user.id,email,stopien:'',imie_nazwisko:email,numer_sluzbowy:'',rola:'funkcjonariusz'},{onConflict:'id'})}msg('registerMsg','Konto utworzone. Możesz się zalogować.',true);setTimeout(()=>{showLoginView();document.getElementById('loginEmail').value=email},1200)}
async function login(){const raw=document.getElementById('loginEmail').value.trim(),email=await resolveLoginToEmail(raw),password=document.getElementById('loginPassword').value;const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return msg('loginMsg',error.message,false);await enterApp(data.user);await logActivity('logowanie','Użytkownik zalogował się do systemu')}
async function logout(){await logActivity('wylogowanie','Użytkownik wylogował się z systemu');await supabaseClient.auth.signOut();location.reload()}
async function enterApp(user){currentUser=user;document.getElementById('loginView').classList.add('hidden');document.getElementById('registerView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');let {data:profile}=await supabaseClient.from('profile').select('*').eq('id',user.id).maybeSingle();if(!profile){const byEmail=await supabaseClient.from('profile').select('*').eq('email',user.email).maybeSingle();profile=byEmail.data;if(profile&&profile.id!==user.id){await supabaseClient.from('profile').update({id:user.id}).eq('email',user.email);profile.id=user.id}}if(!profile){const p={id:user.id,email:user.email,stopien:'',imie_nazwisko:user.email,numer_sluzbowy:'',rola:'funkcjonariusz'};const {data:c}=await supabaseClient.from('profile').insert(p).select().single();profile=c||p}currentProfile=profile;document.querySelectorAll('.commander-only').forEach(e=>e.classList.add('hidden'));const display=`${profile.stopien||''} ${profile.imie_nazwisko||user.email}`.trim();document.getElementById('userInfo').textContent=`${display} | ${profile.email||user.email}`;document.getElementById('rolePill').textContent=profile.rola||'funkcjonariusz';document.getElementById('statRole').textContent=profile.rola||'funkcjonariusz';if(isCommander())document.querySelectorAll('.commander-only').forEach(e=>e.classList.remove('hidden'));await refreshAll()}
function isCommander(){return ['admin','dowodca','zastepca'].includes(currentProfile?.rola)}
async function logActivity(akcja,opis){try{if(!currentProfile)return;await supabaseClient.from('aktywnosc').insert({uzytkownik:currentProfile.imie_nazwisko||currentProfile.email,rola:currentProfile.rola,akcja,opis})}catch(e){}}
async function refreshAll(){await loadPojazdySystem();await policeDocLoadMine();if(isCommander()){await loadProfiles();await loadArchive();await loadActivity();await loadTrash();await loadSettings()}updateStats()}
function refreshCurrentPage(){const id=[...document.querySelectorAll('.page')].find(p=>!p.classList.contains('hidden'))?.id;if(id==='vehicles')loadPojazdySystem();else if(id==='documents')policeDocLoadMine();else if(id==='users')loadProfiles();else if(id==='archive')loadArchive();else if(id==='activity')loadActivity();else if(id==='trash')loadTrash();else if(id==='settings')loadSettings();else refreshAll()}
function showPage(id,btn){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));if(btn)btn.classList.add('active');const t={dashboard:'Pulpit',vehicles:'Pojazdy',documents:'Dokumenty',users:'Funkcjonariusze',archive:'Archiwum',activity:'Aktywność',trash:'Kosz',settings:'Ustawienia'};document.getElementById('pageTitle').textContent=t[id]||'SWD';refreshCurrentPage()}
function quickPage(id){const btn=[...document.querySelectorAll('.nav')].find(b=>b.getAttribute('onclick')?.includes(`'${id}'`));showPage(id,btn)}
async function loadProfiles(){const {data,error}=await supabaseClient.from('profile').select('*').order('created_at',{ascending:false});const box=document.getElementById('profilesList');if(!box)return;if(error){box.innerHTML=`<div class="empty">${error.message}</div>`;return}box.innerHTML=(data||[]).map(p=>`<div class="list-item"><h4>${p.stopien||''} ${p.imie_nazwisko||p.email}</h4><p>Email: ${p.email||''}</p><p>Nr służbowy: ${p.numer_sluzbowy||''}</p><p>Rola: <b>${p.rola||'funkcjonariusz'}</b></p></div>`).join('')||'<div class="empty">Brak funkcjonariuszy.</div>'}
async function loadArchive(){const {data,error}=await supabaseClient.from('dokumenty').select('*').is('deleted_at',null).order('created_at',{ascending:false}).limit(300);const box=document.getElementById('archiveList');if(!box)return;if(error){box.innerHTML=error.message;return}const q=(document.getElementById('archiveSearch')?.value||'').toLowerCase();box.innerHTML=(data||[]).filter(d=>`${d.numer_dokumentu||''} ${d.tytul||''} ${d.funkcjonariusz||''} ${d.status||''}`.toLowerCase().includes(q)).map(d=>`<div class="list-item"><span class="status ${d.status}">${d.status||''}</span><h4>${d.numer_dokumentu||''} ${d.tytul||''}</h4><p>${d.funkcjonariusz||''}</p></div>`).join('')||'<div class="empty">Brak wyników.</div>'}
async function loadActivity(){const {data,error}=await supabaseClient.from('aktywnosc').select('*').order('created_at',{ascending:false}).limit(100);const box=document.getElementById('activityList');if(!box)return;if(error){box.innerHTML=error.message;return}box.innerHTML=(data||[]).map(a=>`<div class="list-item"><h4>${a.akcja||''}</h4><p>${a.opis||''}</p><p class="small">${a.uzytkownik||''} | ${a.rola||''} | ${(a.created_at||'').slice(0,16).replace('T',' ')}</p></div>`).join('')||'<div class="empty">Brak aktywności.</div>'}
async function loadTrash(){const {data,error}=await supabaseClient.from('dokumenty').select('*').not('deleted_at','is',null).order('deleted_at',{ascending:false}).limit(100);const box=document.getElementById('trashList');if(!box)return;if(error){box.innerHTML=error.message;return}box.innerHTML=(data||[]).map(d=>`<div class="list-item"><span class="status usuniety">kosz</span><h4>${d.numer_dokumentu||''} ${d.tytul||''}</h4><p>Usunięto: ${(d.deleted_at||'').slice(0,16).replace('T',' ')} przez ${d.deleted_by||''}</p></div>`).join('')||'<div class="empty">Kosz pusty.</div>'}
async function loadSettings(){const {data}=await supabaseClient.from('numeracja_dokumentow').select('*').order('typ');const box=document.getElementById('numberingSettings');if(box)box.innerHTML=(data||[]).map(n=>`<div class="list-item"><h4>${n.typ}</h4><p>Prefix: <b>${n.prefix}</b> | Rok: ${n.rok} | Ostatni numer: ${n.ostatni_numer}</p></div>`).join('')}
function updateStats(){document.getElementById('statVehicles').textContent=(window.pojazdyLista||[]).length||0;document.getElementById('statPatrol').textContent=(window.aktywneKartyPojazdow||[]).length||0;document.getElementById('statDocs').textContent=document.querySelectorAll('#myDocsList .list-item').length||0}
init();